### ISSUE TITLE
Update issue tags and projects

### ISSUE THREAD

**Issue by mhm1117** [cse110-fa22-group6/cse110-fa22-group6#79]
### To-Do:
- [x] Add additional issue tags and clean them up
- [x] Update existing issues with all the relevant tags

**Comment by mhm1117** [comment]
Add To-Do:
- [ ] add all relevant issues pull requests to sprint 1 project
